---
- name: Get Linux Server CPU Utilization
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get CPU utilization
      command: |
        mpstat
      register: cpu_utilization

    - name: Display CPU utilization
      debug:
        var: cpu_utilization.stdout_lines[0]
